---
title: "delet"
author: "sbsambado"
date: "4/20/2020"
output: html_document
---
  
When we want ot ask a question about the mean of a sample, but we do not know there true variance of the population (i.e. we have to estimate the variance from the sample) we need to use a one sample t-test. The one-sample t-test has the following assumptions:  
  
1. Assumes the random variable (e.g. beak width, kelp height, etc.) has a *normal distribution*  
2. Assumes that the observations represent a *random sample* from the population  
  
The hypotheses for a two-sided one sample t-test are: 

$H_0 : \mu = a$  
$H_A : \mu \neq a$  
where $a$ is your hypothezied mean.  
  
To test these hypotheses, calculate a t statistic using the following formula:  
  
$t = \frac{\bar Y - a}{s/\sqrt{n}}$  
  
where $s$ is the standard deviation of your sample and n is your sample size.  
  
The resulting t-statistic has $n-1$ degrees of freedom (df). You can test your null hypothesis in three different ways:   
  
1. Get the critical t-value $(t_{\alpha(2)})$ with $n-1$ df for $\alpha = 0.05$ and compare it to your calculated t-value. Reject your null hypothesis if the absolute value of your t-value is greater than the absolute value or the critical t-value.  
2. Calculate the 95% confidence interval with the equation $\bar Y \pm t_{\alpha(2),df}SE_{\bar Y}$ and determine if $a$ (your hypothesized mean) is in the interval. Reject your null hypothesis if $a$ is not in the 95% CI.    
3. Find the p-value associated with your critical t-value (via R or a t-table with $n-1$ df) and determine if it is less than your predetermined $\alpha$. Reject $H_0$ if $p<\alpha$  
  
#### 1.2 Paired t-test  
  
If you want to compare the means between two groups and each data point in one group is uniquely paired with a data point in another group you can use the paired t-test. Take the difference between each pair of data points and then perform a one sample t-test with $H_0 : \mu_d = 0$. Assumptions:  
  
1. Assumes that the observations from each group represent a *random sample* from the population.  
2. Assumes that the *difference* of the two observations follow a *normal distribution*.  
  
#### 1.3 Two-sample t-test  
  
The two-sample t-test compares whether the means of two groups are significantly different form each other. This test has the following assumptions:  
  
1. Assumes that the observations from *each group* represent a *random sample* from the population.  
2. Assumes that the observations follow a *normal distribution*.  
3. Assumes that the observations from the two groups have *the same variance*.    
  
If we ahve two groups called group 1 and group 2, the two-sided hypothes for the two-sample t-test are:  
  
$H_0 : \mu_1 = \mu_2$  
$H_A : \mu_1 \neq \mu_2$  
  
Before we can test these hypotheses we need to ensure that our assumptions are met. You can test the normality assumption using any of the procedures that you already know (e.g. qqplots or the Shapiro Wilk statistic). To test the homogeneity (equal) of variance assumption we will use something called *Levene's Test*. The *null hypothesis* of the Levene's test is that the variance between the two groups are equal. The *alternative hypothesis* is that they are not equal.  
If we fail to reject the *null hypothesis* of the Levene's test we can pool our variances and use a standard two-sample t-test. We would compute this t statistic using the following equations:  
  
$SE_{\bar Y_1 - \bar Y_2} = \sqrt{s^2_p(\frac{1}{n_1}+\frac{1}{n_2})}$  
  
where  
  
$s^2_p = \frac{df_1s^2_1+df_2s^2_2}{df_1+df_2}$  
  
is the pooled sample variance (described in your book). With these equations we can calculate the t statistic:  
  
$t = \frac{\bar Y_1 - \bar Y_2}{SE_{\bar Y_1 - \bar Y_2}}$  